#
# Module manifest for module 'M365IncidentResponseTools'
#
# Generated by: DrollRobot
#
# Generated on: 3/1/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'M365IncidentResponseTools.psm1'

    # Version number of this module.
    ModuleVersion     = '2.9.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '1e770097-ca3d-4caa-a57e-2d5040f11664'

    # Author of this module
    Author            = 'DrollRobot'

    # Company or vendor of this module
    CompanyName       = 'Unknown'

    # Copyright statement for this module
    Copyright         = '(c) DrollRobot. All rights reserved.'

    # Description of the functionality provided by this module
    # Description = ''

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.5'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is
    # valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module.
    # This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        # Microsoft.Graph pinned to 2.33.0 for now due to auth changes in 2.34.0
        @{ModuleName = 'Microsoft.Graph.Applications'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.DeviceManagement'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Beta.Identity.Signins'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Beta.Reports'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.DirectoryObjects'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Groups'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Identity.DirectoryManagement'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Identity.Signins'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Reports'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Users'; RequiredVersion = '2.33.0'}
        @{ModuleName = 'Microsoft.Graph.Users.Actions'; RequiredVersion = '2.33.0'}

        @{ModuleName = 'ExchangeOnlineManagement'; ModuleVersion = '3.4.0'}
        @{ModuleName = 'ImportExcel';             ModuleVersion = '7.8.0'}
        @{ModuleName = 'PSToml';                  ModuleVersion = '0.3.0'}

        # Dev/test dependencies -- not required at runtime.
        # @{ModuleName = 'Pester';  ModuleVersion = '5.0.0'}
        # @{ModuleName = 'PlatyPS'; ModuleVersion = '0.14.0'}
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # Runs in caller scope (not module scope), so functions defined here are NOT tracked by
    # the module and survive Import-Module -Force reimports.
    ScriptsToProcess  = @(
        'module_init\Initialize-IRT.ps1'
    )

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # Scripts are dot-sourced dynamically in M365IncidentResponseTools.psm1
    # NestedModules     = @()

    # Functions to export from this module, for best performance, do not use wildcards and
    # do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        ### devices
        'Disable-IRTDevice'
        'Enable-IRTDevice'
        'Find-IRTDevice'
        'Remove-IRTDevice'
        'Show-IRTDevice'

        ### connect
        'Connect-IRT'
        'Connect-IRTExchange'
        'Connect-IRTGraph'
        'Connect-IRTIPPS'
        'Connect-IRTTenant'
        'Disconnect-IRT'
        'Test-IRTConnection'
        'Clear-IRTTokenCache'
        'Open-IRTTenantSheet'
        'Update-IRTToken'

        ### entra_logs
        'Get-EntraAuditLog'
        'Show-EntraAuditLog'
        'Get-IRTServicePrincipalSignInLog'
        'Get-NonInteractiveLog'
        'Get-SignInLog'
        'Show-IRTServicePrincipalSignInLog'
        'Show-SignInLog'

        ### onprem_ad
        'Find-IRTAdDevice'
        'Find-IRTAdOu'
        'Find-IRTAdUser'
        'Find-IRTAllDomainController'
        'Get-IRTAdAdminUser'
        'Disable-IRTAdUser'
        'Enable-IRTAdUser'
        'Push-IRTAdSync'
        'Reset-IRTAdUserPassword'
        'Show-IRTAdDevice'
        'Show-IRTAdOus'
        'Show-IRTAdUser'

        ### mailbox
        'Get-IRTInboxRule'
        'Get-UserMailboxPermission'
        'Grant-MailboxFullAccess'
        'Open-MailboxInOWA'
        'Remove-MailboxFullAccess'
        'Show-Mailbox'
        'Show-MailboxAccess'

        ### message_trace
        'Get-IRTMessageTrace'
        'Show-IRTMessageTrace'

        ### modules
        'Compress-InvestigationFolder'
        'Copy-IRTFunction'
        'Find-GraphDirectoryObject'
        'Import-IRT'
        'Import-IRTConfig'
        'Open-IRTConfig'
        'Get-IRTUserObject'
        'Import-LogFile'
        'New-InvestigationFolder'
        'Request-DirectoryRole'
        'Request-DirectoryRoleTemplate'
        'Request-GraphGroup'
        'Request-GraphOauth2Grant'
        'Request-GraphDevice'
        'Request-GraphServicePrincipal'
        'Request-GraphUser'
        'Get-LicenseReport'
        'Resolve-IRTDateRange'
        'Set-IRTConfig'
        'Start-IRTPlaybook'
        'Write-IRT'

        ### roles
        'Get-AdminRole'

        ### service_principals
        'Find-RiskyServicePrincipal'
        'Find-IRTServicePrincipal'
        'Get-IRTTenantInfo'
        'Get-UserServicePrincipal'
        'Show-IRTServicePrincipal'
        'Show-TenantServicePrincipal'

        ### unified_audit_log
        'Get-UALog'
        'Open-IRTAllOperationsSheet'
        'Show-UALog'

        ### users
        'Disable-GraphUser'
        'Enable-GraphUser'
        'Find-IRTUser'
        'Reset-IRTUserPassword'
        'Revoke-UserSession'
        'Set-UsageLocation'
        'Show-IRTUser'
        'Show-UserMFA'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and
    # do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and
    # do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @(

        ### connect
        # Connect-IRT
        'ConnectIRT'
        # Connect-IRTTenant
        'IRTTenant'
        # Open-IRTTenantSheet
        'Open-IRTTenantWorksheet'
        'OpenIRTTenantWorksheet'
        'OpenIRTTenantSheet'
        'IRTTenantSheet'
        # Disconnect-IRT
        'DisconnectIRT'
        'IRTDisconnect'
        # Clear-IRTTokenCache
        'ClearIRTTokenCache'

        ### devices
        # Disable-IRTDevice
        'DisableDevice'
        'DisableDevices'
        # Enable-IRTDevice
        'EnableDevice'
        'EnableDevices'
        # Find-IRTDevice
        'FindDevice'
        'FindDevices'
        # Remove-IRTDevice
        'DeleteDevice'
        'DeleteDevices'
        'RemoveDevice'
        'RemoveDevices'
        # Show-IRTDevice
        'Show-IRTDevices'
        'Show-Device'
        'Show-Devices'
        'ShowIRTDevice'
        'ShowIRTDevices'
        'ShowDevice'
        'ShowDevices'

        ### entra_logs
        # Get-EntraAuditLogs
        'EALog'
        'EALogs'
        'GetEALog'
        'GetEALogs'
        # Get-NonInteractiveLogs
        'GetNILog'
        'GetNILogs'
        'NILog'
        'NILogs'
        # Get-SignInLogs
        'GetSILog'
        'GetSILogs'
        'SILog'
        'SILogs'
        # Get-IRTServicePrincipalSignInLog
        'GetSPSILog'
        'GetSPSILogs'
        'SPSILog'
        'SPSILogs'

        ### onprem_ad
        # Find-IRTAdDevice
        'Find-IRTAdDevices'
        'Find-AdDevice', 'Find-AdDevices'
        'FindIRTAdDevice', 'FindIRTAdDevices'
        'FindAdDevice', 'FindAdDevices'
        # Find-IRTAdOu
        'Find-IRTAdOus'
        'Find-AdOu', 'Find-AdOus'
        'FindIRTAdOu', 'FindIRTAdOus'
        'FindAdOu', 'FindAdOus'
        # Find-IRTAdUser
        'Find-IRTAdUsers'
        'Find-AdUser', 'Find-AdUsers'
        'FindIRTAdUser', 'FindIRTAdUsers'
        'FindAdUser', 'FindAdUsers'
        # Find-IRTAllDomainController
        'Find-IRTAllDomainControllers'
        'Find-AllDomainController', 'Find-AllDomainControllers'
        'FindIRTAllDomainController', 'FindIRTAllDomainControllers'
        'FindAllDomainController', 'FindAllDomainControllers'
        'Find-IRTDomainController', 'Find-IRTDomainControllers'
        'Find-DomainController', 'Find-DomainControllers'
        'FindIRTDomainController', 'FindIRTDomainControllers'
        'FindDomainController', 'FindDomainControllers'
        'Find-IRTDC', 'Find-IRTDCs'
        'Find-DC', 'Find-DCs'
        'FindIRTDC', 'FindIRTDCs'
        'FindDC', 'FindDCs'
        # Get-IRTAdAdminUser
        'Get-IRTAdAdminUsers'
        'Get-AdAdminUser', 'Get-AdAdminUsers'
        'GetIRTAdAdminUser', 'GetIRTAdAdminUsers'
        'GetAdAdminUser', 'GetAdAdminUsers'
        'GetAdAdmins', 'AdAdmins'
        # Disable-IRTAdUser
        'Disable-IRTAdUsers'
        'Disable-AdUser', 'Disable-AdUsers'
        'DisableIRTAdUser', 'DisableIRTAdUsers'
        'DisableAdUser', 'DisableAdUsers'
        'Lock-IRTAdUser', 'Lock-IRTAdUsers'
        'Lock-AdUser', 'Lock-AdUsers'
        'LockIRTAdUser', 'LockIRTAdUsers'
        'LockAdUser', 'LockAdUsers'
        # Enable-IRTAdUser
        'Enable-IRTAdUsers'
        'Enable-AdUser', 'Enable-AdUsers'
        'EnableIRTAdUser', 'EnableIRTAdUsers'
        'EnableAdUser', 'EnableAdUsers'
        'Unlock-IRTAdUser', 'Unlock-IRTAdUsers'
        'Unlock-AdUser', 'Unlock-AdUsers'
        'UnlockIRTAdUser', 'UnlockIRTAdUsers'
        'UnlockAdUser', 'UnlockAdUsers'
        # Push-IRTAdSync
        'Push-IRTAdSyncs'
        'Push-AdSync', 'Push-AdSyncs'
        'PushIRTAdSync', 'PushIRTAdSyncs'
        'PushAdSync', 'PushAdSyncs'
        'AdSync', 'SyncAd'
        # Reset-IRTAdUserPassword
        'ResetAdPassword'
        'ResetAdPasswords'
        'Reset-AdPassword'
        # Show-IRTAdOus
        'Show-IRTAdOu'
        'Show-AdOu', 'Show-AdOus'
        'ShowIRTAdOu', 'ShowIRTAdOus'
        'ShowAdOu', 'ShowAdOus'
        'AdOus'
        # Show-IRTAdDevice
        'Show-IRTAdDevices'
        'Show-AdDevice'
        'Show-AdDevices'
        'ShowIRTAdDevice'
        'ShowIRTAdDevices'
        'ShowAdDevice'
        'ShowAdDevices'
        # Show-IRTAdUser
        'Show-IRTAdUsers'
        'Show-AdUser'
        'Show-AdUsers'
        'ShowIRTAdUser'
        'ShowIRTAdUsers'
        'ShowAdUser'
        'ShowAdUsers'

        ### mailbox
        # Get-IRTInboxRules
        'InboxRule'
        'InboxRules'
        # Grant-MailboxFullAccess
        'FullAccess'
        # Open-MailboxInOWA
        'OpenMailbox'
        # Remove-MailboxFullAccess
        'RemoveFullAccess'
        # Show-Mailbox
        'ShowMailbox'
        # Show-MailboxAccess
        'MailboxAccess'
        'ShowAccess'
        'ShowFullAccess'

        ### message_trace
        # Get-IRTMessageTrace
        'MessageTrace'

        ### modules
        # Import-IRT
        'ImportIRT'
        'LoadIRT'
        'IRT'
        # Copy-IRTFunction
        'Copy-IRTFunctions'
        'CopyIRTFunctions'
        'CopyIRTFunction'
        'IRTFunction'
        'IRTFunctions'
        # Import-IRTConfig / Open-IRTConfig / Set-IRTConfig
        'ImportConfig'
        'OpenConfig'
        'SetConfig'
        'IRTConfig'
        # Import-LogFile
        'ImportLog'
        'ImportLogs'
        # New-InvestigationFolder
        'NewDir'
        'NewFolder'
        # Start-IRTPlaybook
        'Playbook'

        ### roles
        # Get-AdminRoles
        'GetAdmins'

        ### service_principals
        # Find-IRTServicePrincipal
        'Find-IRTServicePrincipals'
        'Find-ServicePrincipal', 'Find-ServicePrincipals'
        'FindIRTServicePrincipal', 'FindIRTServicePrincipals'
        'FindServicePrincipal', 'FindServicePrincipals'
        'Find-IRTSP', 'Find-IRTSPs'
        'Find-SP', 'Find-SPs'
        'FindIRTSP', 'FindIRTSPs'
        'FindSP', 'FindSPs'
        'Find-IRTEnterpriseApplication', 'Find-IRTEnterpriseApplications'
        'Find-EnterpriseApplication', 'Find-EnterpriseApplications'
        'FindIRTEnterpriseApplication', 'FindIRTEnterpriseApplications'
        'FindEnterpriseApplication', 'FindEnterpriseApplications'
        # Show-IRTServicePrincipal
        'Show-IRTServicePrincipals'
        'Show-ServicePrincipal'
        'ShowIRTServicePrincipal', 'ShowIRTServicePrincipals'
        'ShowServicePrincipal', 'ShowServicePrincipals'
        'ShowSP', 'ShowSPs'
        'ShowApp', 'ShowApps'
        'ShowApplication', 'ShowApplications'
        'ShowEnterpriseApp', 'ShowEnterpriseApps'
        'ShowEnterpriseApplication', 'ShowEnterpriseApplications'
        # Show-TenantServicePrincipal
        'ShowTenantServicePrincipal', 'ShowTenantServicePrincipals'
        'ShowTenantSP', 'ShowTenantSPs'
        'ShowTenantApp', 'ShowTenantApps'
        'ShowTenantApplication', 'ShowTenantApplications'
        'ShowTenantEnterpriseApp', 'ShowTenantEnterpriseApps'
        'ShowAllServicePrincipals', 'ShowAllSPs'
        'ShowAllApps', 'ShowAllApplications', 'ShowAllEnterpriseApps'
        'Show-Apps', 'Show-ServicePrincipals', 'Show-EnterpriseApps', 'Show-Applications'
        # Find-RiskyServicePrincipal
        'RiskyApps', 'RiskySPs'
        'FindRiskySP', 'FindRiskySPs'
        'FindRiskyApp', 'FindRiskyApps'
        'FindRiskyApplication', 'FindRiskyApplications'
        'FindRiskyServicePrincipal', 'FindRiskyServicePrincipals'
        'FindRiskyEnterpriseApp', 'FindRiskyEnterpriseApps'
        'Find-RiskyApplication'
        # Get-UserServicePrincipal
        'UserApps', 'UserSPs'
        'GetUserSP', 'GetUserSPs'
        'GetUserApp', 'GetUserApps'
        'GetUserApplication', 'GetUserApplications'
        'GetUserServicePrincipal', 'GetUserServicePrincipals'
        'GetUserEnterpriseApp', 'GetUserEnterpriseApps'
        'Get-UserApplication'

        ### unified_audit_log
        # Get-UALogs
        'GetUALog'
        'GetUALogs'
        'UALog'
        'UALogs'
        # Open-IRTAllOperationsSheet
        'Open-AllOperationsSheet'
        'IRTAllOperationsSheet'

        ### users
        # Find-IRTUser
        'Find-IRTUsers', 'FindIRTUser', 'FindIRTUsers'
        'Find-User', 'Find-Users', 'FindUser', 'FindUsers'
        # Disable-GraphUsers
        'DisableUser'
        'DisableUsers'
        'Lock-GraphUsers'
        'LockUser'
        'LockUsers'
        # Reset-IRTUserPassword
        'ResetPassword'
        'ResetPasswords'
        # Revoke-UsersSessions
        'RevokeSessions'
        # Set-UsageLocation
        'SetLocation'
        'SetUsage'
        # Show-IRTUser
        'Show-IRTUsers'
        'Show-User'
        'Show-Users'
        'ShowIRTUser'
        'ShowIRTUsers'
        'ShowUser'
        'ShowUsers'
        # Show-UserMFA
        'ShowMFA'
        'UserMFA'
        # Enable-GraphUsers
        'EnableUser'
        'EnableUsers'
        'Unlock-GraphUsers'
        'UnlockUser'
        'UnlockUsers'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also
    # contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for
            # install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using
    # Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
