site_name: M365 Incident Response Tools
site_description: PowerShell module for Microsoft 365 incident response investigations.
site_url: https://DrollRobot.github.io/M365IncidentResponseTools/
repo_url: https://github.com/DrollRobot/M365IncidentResponseTools
repo_name: DrollRobot/M365IncidentResponseTools
docs_dir: Docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Connect to M365: connect.md
  - Investigation:
    - Users: investigation-user.md
    - Service Principals: investigation-sp.md
  - Devices: devices.md
  - Remediation:
    - M365: remediation-user.md
    - On-Premises AD: remediation-ad.md
  - Command Reference:
    - Playbook:
      - Start-IRTPlaybook: M365IncidentResponseTools/Start-IRTPlaybook.md
    - Connect:
      - Clear-IRTTokenCache: M365IncidentResponseTools/Clear-IRTTokenCache.md
      - Connect-IRT: M365IncidentResponseTools/Connect-IRT.md
      - Connect-IRTRunspaceExchange: M365IncidentResponseTools/Connect-IRTRunspaceExchange.md
      - Connect-IRTTenant: M365IncidentResponseTools/Connect-IRTTenant.md
      - Disconnect-IRT: M365IncidentResponseTools/Disconnect-IRT.md
      - Get-IRTAccessToken: M365IncidentResponseTools/Get-IRTAccessToken.md
      - Open-IRTTab: M365IncidentResponseTools/Open-IRTTab.md
      - Test-IRTConnection: M365IncidentResponseTools/Test-IRTConnection.md
      - Update-IRTToken: M365IncidentResponseTools/Update-IRTToken.md
    - Devices:
      - Disable-IRTDevice: M365IncidentResponseTools/Disable-IRTDevice.md
      - Enable-IRTDevice: M365IncidentResponseTools/Enable-IRTDevice.md
      - Find-IRTDevice: M365IncidentResponseTools/Find-IRTDevice.md
      - Get-IRTAllEntraDevice: M365IncidentResponseTools/Get-IRTAllEntraDevice.md
      - Remove-IRTDevice: M365IncidentResponseTools/Remove-IRTDevice.md
      - Show-IRTDevice: M365IncidentResponseTools/Show-IRTDevice.md
    - Email:
      - Get-IRTEmailSearch: M365IncidentResponseTools/Get-IRTEmailSearch.md
      - Get-IRTMessageTrace: M365IncidentResponseTools/Get-IRTMessageTrace.md
      - New-IRTEmailSearch: M365IncidentResponseTools/New-IRTEmailSearch.md
      - Show-IRTMessageTrace: M365IncidentResponseTools/Show-IRTMessageTrace.md
    - Entra Logs:
      - Get-IRTEntraAuditLog: M365IncidentResponseTools/Get-IRTEntraAuditLog.md
      - Get-IRTEntraSignInLog: M365IncidentResponseTools/Get-IRTEntraSignInLog.md
      - Get-IRTNonInteractiveSignIn: M365IncidentResponseTools/Get-IRTNonInteractiveSignIn.md
      - Get-IRTServicePrincipalSignInLog: M365IncidentResponseTools/Get-IRTServicePrincipalSignInLog.md
      - Show-IRTEntraAuditLog: M365IncidentResponseTools/Show-IRTEntraAuditLog.md
      - Show-IRTEntraSignInLog: M365IncidentResponseTools/Show-IRTEntraSignInLog.md
      - Show-IRTServicePrincipalSignIn: M365IncidentResponseTools/Show-IRTServicePrincipalSignIn.md
    - Mailbox:
      - Add-IRTMailboxFullAccess: M365IncidentResponseTools/Add-IRTMailboxFullAccess.md
      - Get-IRTInboxRule: M365IncidentResponseTools/Get-IRTInboxRule.md
      - Open-IRTMailboxInOwa: M365IncidentResponseTools/Open-IRTMailboxInOwa.md
      - Remove-IRTMailboxFullAccess: M365IncidentResponseTools/Remove-IRTMailboxFullAccess.md
      - Show-IRTMailbox: M365IncidentResponseTools/Show-IRTMailbox.md
      - Show-IRTMailboxAccess: M365IncidentResponseTools/Show-IRTMailboxAccess.md
    - Roles:
      - Get-IRTAdminRole: M365IncidentResponseTools/Get-IRTAdminRole.md
    - Service Principals:
      - Find-IRTRiskyServicePrincipal: M365IncidentResponseTools/Find-IRTRiskyServicePrincipal.md
      - Find-IRTServicePrincipal: M365IncidentResponseTools/Find-IRTServicePrincipal.md
      - Get-IRTServicePrincipal: M365IncidentResponseTools/Get-IRTServicePrincipal.md
      - Get-IRTTenantOwner: M365IncidentResponseTools/Get-IRTTenantOwner.md
      - Get-IRTUserServicePrincipal: M365IncidentResponseTools/Get-IRTUserServicePrincipal.md
      - Open-IRTTenantOwnerCSV: M365IncidentResponseTools/Open-IRTTenantOwnerCSV.md
      - Open-IRTTenantSheet: M365IncidentResponseTools/Open-IRTTenantSheet.md
      - Show-IRTServicePrincipal: M365IncidentResponseTools/Show-IRTServicePrincipal.md
    - Unified Audit Log:
      - Get-IRTUnifiedAuditLog: M365IncidentResponseTools/Get-IRTUnifiedAuditLog.md
      - Open-IRTAllOperationsSheet: M365IncidentResponseTools/Open-IRTAllOperationsSheet.md
      - Show-IRTUnifiedAuditLog: M365IncidentResponseTools/Show-IRTUnifiedAuditLog.md
    - Users:
      - Disable-IRTUser: M365IncidentResponseTools/Disable-IRTUser.md
      - Enable-IRTUser: M365IncidentResponseTools/Enable-IRTUser.md
      - Find-IRTUser: M365IncidentResponseTools/Find-IRTUser.md
      - Reset-IRTUserPassword: M365IncidentResponseTools/Reset-IRTUserPassword.md
      - Revoke-IRTUserSession: M365IncidentResponseTools/Revoke-IRTUserSession.md
      - Set-IRTUserUsageLocation: M365IncidentResponseTools/Set-IRTUserUsageLocation.md
      - Show-IRTUser: M365IncidentResponseTools/Show-IRTUser.md
      - Show-IRTUserMfa: M365IncidentResponseTools/Show-IRTUserMfa.md
    - Utilities:
      - Compress-IRTInvestigationFolder: M365IncidentResponseTools/Compress-IRTInvestigationFolder.md
      - Copy-IRTFunction: M365IncidentResponseTools/Copy-IRTFunction.md
      - Find-IRTDirectoryObject: M365IncidentResponseTools/Find-IRTDirectoryObject.md
      - Get-IRTLicenseReport: M365IncidentResponseTools/Get-IRTLicenseReport.md
      - Get-TenantOidc: M365IncidentResponseTools/Get-TenantOidc.md
      - Import-IRT: M365IncidentResponseTools/Import-IRT.md
      - Import-IRTConfig: M365IncidentResponseTools/Import-IRTConfig.md
      - New-IRTInvestigationFolder: M365IncidentResponseTools/New-IRTInvestigationFolder.md
      - Open-IRTConfig: M365IncidentResponseTools/Open-IRTConfig.md
      - Set-IRTConfig: M365IncidentResponseTools/Set-IRTConfig.md
    - On-Premises AD:
      - Disable-IRTAdUser: M365IncidentResponseTools/Disable-IRTAdUser.md
      - Enable-IRTAdUser: M365IncidentResponseTools/Enable-IRTAdUser.md
      - Find-IRTAdDevice: M365IncidentResponseTools/Find-IRTAdDevice.md
      - Find-IRTAdOu: M365IncidentResponseTools/Find-IRTAdOu.md
      - Find-IRTAdUser: M365IncidentResponseTools/Find-IRTAdUser.md
      - Find-IRTDomainController: M365IncidentResponseTools/Find-IRTDomainController.md
      - Get-IRTAdAdminUser: M365IncidentResponseTools/Get-IRTAdAdminUser.md
      - Push-IRTAdSync: M365IncidentResponseTools/Push-IRTAdSync.md
      - Reset-IRTAdUserPassword: M365IncidentResponseTools/Reset-IRTAdUserPassword.md
      - Show-IRTAdDevice: M365IncidentResponseTools/Show-IRTAdDevice.md
      - Show-IRTAdOus: M365IncidentResponseTools/Show-IRTAdOus.md
      - Show-IRTAdUser: M365IncidentResponseTools/Show-IRTAdUser.md
