#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }

<#
.SYNOPSIS
    Offline branch tests for Connect-IRTExchange.

.DESCRIPTION
    All tests are offline. Get-IRTAccessToken, Get-TokenPayload,
    Get-ConnectionInformation, Connect-ExchangeOnline, Disconnect-ExchangeOnline,
    Get-OrganizationConfig, and Write-IRT are mocked. The connection registry is
    simulated with a script-scoped list: the Connect-ExchangeOnline mock appends
    a new Connected entry exactly like the real module would, so the
    pre/post-ConnectionId diffing logic is exercised for real.

    Get-OrganizationConfig only exists after a real connect (it lives in the
    dynamically generated tmpEXO module), so a global stub function is defined
    in BeforeAll to make it mockable offline and removed in AfterAll.

-- fresh connect -----------------------------------------------------------

    No existing EXO connection: the connector must mint, bind via
    Connect-ExchangeOnline (UPN from the token result, cloud environment name),
    record the NEW ConnectionId, and disconnect nothing.

-- cloud (aud) validation --------------------------------------------------

    Same contract as Graph: unparseable/GUID audiences are ignored; a wrong
    audience triggers exactly one -ForceRefresh re-acquisition; a still-wrong
    audience throws.

-- already connected --------------------------------------------------------

    A healthy connection for the tenant (non-IPPS), a bound token that is not
    stale, and no newer token in hand: verify liveness via Get-OrganizationConfig
    and do NOT reconnect. An IPPS-only connection must NOT count as an Exchange
    connection.

-- scoped reconnect ---------------------------------------------------------

    When a reconnect happens with an existing connection, the OLD connection
    must be disconnected by -ConnectionId AFTER the new one is established,
    and the IPPS connection must never be touched.
#>

InModuleScope M365IncidentResponseTools {

    BeforeAll {
        $script:TestTenant = 'aaaaaaaa-0000-0000-0000-aaaaaaaaaaaa'

        # Get-OrganizationConfig is generated by the EXO module at connect time
        # and does not exist offline; define a global stub so Mock can bind it.
        function Global:Get-OrganizationConfig { [pscustomobject]@{ Name = 'stub' } }

        function New-TestSession {
            [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
                'PSUseShouldProcessForStateChangingFunctions', '',
                Justification = 'Test-only factory helper; ShouldProcess is not applicable.')]
            param(
                [object] $Exchange = $null,
                [object] $IPPS = $null
            )
            [pscustomobject]@{
                TenantId      = $script:TestTenant
                ClientId      = $null
                Cloud         = 'Commercial'
                CloudConfig   = [pscustomobject]@{
                    LoginHost      = 'https://login.microsoftonline.com'
                    Graph          = 'https://graph.microsoft.com'
                    GraphEnv       = 'Global'
                    Exchange       = 'https://outlook.office365.com/.default'
                    ExchangeEnv    = 'O365Default'
                    IPPS           = 'https://ps.compliance.protection.outlook.com/powershell'
                    IPPSSearchOnly = 'https://dataservice.o365filtering.com/.default'
                }
                Apps          = [hashtable]::Synchronized(@{})
                StickyAccount = [hashtable]::Synchronized(@{})
                Graph         = $null
                Exchange      = $Exchange
                IPPS          = $IPPS
            }
        }

        function New-TokenResult {
            [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
                'PSUseShouldProcessForStateChangingFunctions', '',
                Justification = 'Test-only factory helper; ShouldProcess is not applicable.')]
            param(
                [string] $AccessToken = 'good-token',
                [string] $Username = 'admin@customer.com',
                [System.DateTimeOffset] $ExpiresOn = [System.DateTimeOffset]::UtcNow.AddMinutes(55)
            )
            [pscustomobject]@{
                AccessToken = $AccessToken
                ExpiresOn   = $ExpiresOn
                Account     = [pscustomobject]@{
                    Username      = $Username
                    HomeAccountId = [pscustomobject]@{
                        Identifier = "$Username.home"
                        TenantId   = $script:TestTenant
                    }
                }
            }
        }

        # Connection-registry entry shaped like Get-ConnectionInformation output.
        function New-TestConnection {
            [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
                'PSUseShouldProcessForStateChangingFunctions', '',
                Justification = 'Test-only factory helper; ShouldProcess is not applicable.')]
            param(
                [string] $ConnectionId = ([guid]::NewGuid().ToString()),
                [string] $TenantID = $script:TestTenant,
                [string] $ConnectionUri = 'https://outlook.office365.com',
                [string] $State = 'Connected'
            )
            [pscustomobject]@{
                ConnectionId  = $ConnectionId
                TenantID      = $TenantID
                ConnectionUri = $ConnectionUri
                State         = $State
            }
        }
    }

    AfterAll {
        Remove-Item -Path 'function:Global:Get-OrganizationConfig' -ErrorAction SilentlyContinue
    }

    Describe 'Connect-IRTExchange' {

        BeforeEach {
            $script:SavedSession = (
                Get-Variable -Name IRT_Session -Scope Global -ErrorAction SilentlyContinue
            )?.Value
            $Global:IRT_Session = New-TestSession

            # Simulated EXO connection registry. Connect-ExchangeOnline appends
            # a new entry; Get-ConnectionInformation reads the current state.
            $script:Connections = @()
            Mock Get-ConnectionInformation { $script:Connections }
            Mock Connect-ExchangeOnline {
                $script:NewConnectionId = [guid]::NewGuid().ToString()
                $script:Connections += New-TestConnection -ConnectionId $script:NewConnectionId
            }
            Mock Disconnect-ExchangeOnline {
                $script:Connections = @($script:Connections |
                        Where-Object { $_.ConnectionId -notin $ConnectionId })
            }
            Mock Get-OrganizationConfig { [pscustomobject]@{ Name = 'contoso' } }
            Mock Get-IRTAccessToken { New-TokenResult }
            Mock Get-TokenPayload {
                [pscustomobject]@{ aud = 'https://outlook.office365.com' }
            }
            Mock Write-IRT { }
        }
        AfterEach {
            $Global:IRT_Session = $script:SavedSession
        }

        # -------------------------------------------------------------------
        Context 'fresh connect (no existing connection)' {

            It 'binds the token via Connect-ExchangeOnline with UPN and environment' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Connect-ExchangeOnline -Times 1 -Exactly -ParameterFilter {
                    $AccessToken -eq 'good-token' -and
                    $UserPrincipalName -eq 'admin@customer.com' -and
                    $ExchangeEnvironmentName -eq 'O365Default' -and
                    $ShowBanner -eq $false
                }
            }

            It 'records the NEW ConnectionId in the returned metadata' {
                $Result = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                $Result.ConnectionId | Should -Be $script:NewConnectionId
            }

            It 'disconnects nothing' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Disconnect-ExchangeOnline -Times 0
            }

            It 'returns the new metadata shape' {
                $Result = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                $Result.UserPrincipalName | Should -Be 'admin@customer.com'
                $Result.TenantId | Should -Be $script:TestTenant
                $Result.BoundTokenExpiry | Should -BeOfType [System.DateTime]
            }
        }

        # -------------------------------------------------------------------
        Context 'cloud (aud) validation' {

            It 'skips validation when the audience cannot be decoded' {
                Mock Get-TokenPayload { [pscustomobject]@{ aud = $null } }
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Get-IRTAccessToken -Times 1 -Exactly
            }

            It 'skips validation when the audience is a GUID, not a URL' {
                Mock Get-TokenPayload {
                    [pscustomobject]@{ aud = '00000002-0000-0ff1-ce00-000000000000' }
                }
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Get-IRTAccessToken -Times 1 -Exactly
            }

            It 're-acquires with -ForceRefresh on audience mismatch, then succeeds' {
                Mock Get-IRTAccessToken {
                    if ($ForceRefresh) { New-TokenResult -AccessToken 'right-token' }
                    else { New-TokenResult -AccessToken 'wrong-token' }
                }
                Mock Get-TokenPayload {
                    if ($Token -eq 'wrong-token') {
                        [pscustomobject]@{ aud = 'https://outlook.office365.us' }
                    } else {
                        [pscustomobject]@{ aud = 'https://outlook.office365.com' }
                    }
                }
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Get-IRTAccessToken -Times 1 -Exactly -ParameterFilter {
                    $ForceRefresh -eq $true
                }
            }

            It 'throws when the audience is still wrong after the forced refresh' {
                Mock Get-TokenPayload {
                    [pscustomobject]@{ aud = 'https://outlook.office365.us' }
                }
                { Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial } |
                    Should -Throw -ExpectedMessage '*still does not match*'
            }
        }

        # -------------------------------------------------------------------
        Context 'already connected (healthy connection, same token)' {

            BeforeEach {
                $script:FixedExpiresOn = [System.DateTimeOffset]::UtcNow.AddMinutes(50)
                $script:ExistingId = [guid]::NewGuid().ToString()
                $script:Connections = @(
                    New-TestConnection -ConnectionId $script:ExistingId
                )
                $Global:IRT_Session = New-TestSession -Exchange ([pscustomobject]@{
                        UserPrincipalName = 'admin@customer.com'
                        BoundTokenExpiry  = $script:FixedExpiresOn.UtcDateTime
                        ConnectionId      = $script:ExistingId
                        TenantId          = $script:TestTenant
                    })
                Mock Get-IRTAccessToken { New-TokenResult -ExpiresOn $script:FixedExpiresOn }
            }

            It 'does not reconnect' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Connect-ExchangeOnline -Times 0
            }

            It 'verifies the existing connection with a live call' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Get-OrganizationConfig -Times 1
            }

            It 'returns the existing ConnectionId' {
                $Result = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                $Result.ConnectionId | Should -Be $script:ExistingId
            }

            It 'reconnects when the live verification fails' {
                Mock Get-OrganizationConfig { throw 'session is dead' }
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Connect-ExchangeOnline -Times 1
            }

            It 'reconnects when the bound token is stale (<5 min)' {
                $Stale = [System.DateTimeOffset]::UtcNow.AddMinutes(2)
                $Global:IRT_Session.Exchange.BoundTokenExpiry = $Stale.UtcDateTime
                Mock Get-IRTAccessToken { New-TokenResult -ExpiresOn $script:FixedExpiresOn }
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Connect-ExchangeOnline -Times 1
            }

            It 'reconnects when -Force is set' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial -Force
                Should -Invoke Connect-ExchangeOnline -Times 1
            }

            It 'an IPPS-only connection does not count as an Exchange connection' {
                $IppsUri = 'https://nam02b.ps.compliance.protection.outlook.com/powershell'
                $script:Connections = @(
                    New-TestConnection -ConnectionUri $IppsUri
                )
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Connect-ExchangeOnline -Times 1
            }
        }

        # -------------------------------------------------------------------
        Context 'scoped reconnect cleanup' {

            BeforeEach {
                $script:OldId = [guid]::NewGuid().ToString()
                $script:IppsId = [guid]::NewGuid().ToString()
                $IppsUri = 'https://nam02b.ps.compliance.protection.outlook.com/powershell'
                $script:Connections = @(
                    (New-TestConnection -ConnectionId $script:OldId),
                    (New-TestConnection -ConnectionId $script:IppsId -ConnectionUri $IppsUri)
                )
                $Global:IRT_Session = New-TestSession -Exchange ([pscustomobject]@{
                        UserPrincipalName = 'admin@customer.com'
                        BoundTokenExpiry  = [datetime]::UtcNow.AddMinutes(2)  # stale
                        ConnectionId      = $script:OldId
                        TenantId          = $script:TestTenant
                    })
            }

            It 'disconnects the replaced connection by ConnectionId' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Disconnect-ExchangeOnline -Times 1 -Exactly -ParameterFilter {
                    $ConnectionId -eq $script:OldId
                }
            }

            It 'never issues an unscoped disconnect' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Disconnect-ExchangeOnline -Times 0 -ParameterFilter {
                    -not $ConnectionId
                }
            }

            It 'leaves the IPPS connection alone' {
                $null = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                Should -Invoke Disconnect-ExchangeOnline -Times 0 -ParameterFilter {
                    $ConnectionId -eq $script:IppsId
                }
                $script:Connections.ConnectionId | Should -Contain $script:IppsId
            }

            It 'the new connection survives the cleanup' {
                $Result = Connect-IRTExchange -TenantId $script:TestTenant -Cloud Commercial
                $script:Connections.ConnectionId | Should -Contain $Result.ConnectionId
                $script:Connections.ConnectionId | Should -Not -Contain $script:OldId
            }
        }
    }
}
